#!/usr/bin/env python3
"""
analyze.py -- A3. The corrected cross-language comparison.

4 tokenizers x 7 languages x 5 denominators x 2 corpora, micro-averaged.

The point of the table is not any single cell.  It is that the *ranking and
magnitude of the "Indic penalty" changes by ~4x depending on which
denominator you pick*, from the identical token counts -- so the denominator
is the entire finding, and REPORT_v0 never justified its choice.

Run:
    python analyze.py                          # writes results/a3_*.{md,csv}
    python analyze.py --corpus flores --tokenizer gpt2
"""
import argparse, csv, json, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tokstats as T

HERE = os.path.dirname(os.path.abspath(__file__))
RES = os.path.join(HERE, "results")
UNITS = ["word", "grapheme", "byte", "codepoint", "sentence"]


def measure(corpus, tokname):
    enc = T.get_encoder(tokname)
    rows = {}
    for lang in T.LANGS:
        lines = T.read_lines(T.corpus_path(corpus, lang))
        rates, tok, units = T.micro(lines, enc, {u: T.DENOMS[u] for u in UNITS})
        rows[lang] = dict(rates=rates, tokens=tok, units=units, n=len(lines))
    # every corpus is line-parallel, so all languages have the same n
    assert len({r["n"] for r in rows.values()}) == 1
    return rows


def emit(corpus, out):
    p = lambda s="": (print(s), out.append(s))
    p(f"\n## corpus = {corpus}  ({measure_cache[corpus]['gpt2']['eng']['n']} parallel sentences)")

    # ---- Table 1: the denominator sensitivity, per tokenizer -------------
    for tokname in T.TOKENIZERS:
        rows = measure_cache[corpus][tokname]
        p(f"\n### tokenizer = {tokname}   (micro-averaged: sum(tokens)/sum(units))")
        p("")
        p("| lang | tok/word | tok/grapheme | tok/byte | tok/sentence | "
          "**cost vs eng** (same 1012 sentences) |")
        p("|---|---|---|---|---|---|")
        e = rows["eng"]
        for lang in T.LANGS:
            r = rows[lang]
            cost = r["tokens"] / e["tokens"]
            star = " ***" if lang != "eng" else ""
            p(f"| {lang} | {r['rates']['word']:.3f} | {r['rates']['grapheme']:.3f} | "
              f"{r['rates']['byte']:.3f} | {r['rates']['sentence']:.2f} | "
              f"**{cost:.2f}x**{star} |")

        # the headline distortion: same tokens, four denominators
        h, en = rows["hin"], rows["eng"]
        p("")
        p(f"hin-vs-eng penalty measured four ways, from the *identical* token counts "
          f"({h['tokens']} hin / {en['tokens']} eng):")
        for u in ("word", "grapheme", "byte", "sentence"):
            p(f"  - per {u:<9}: {h['rates'][u]/en['rates'][u]:6.2f}x")

    # ---- Table 2: why the denominators disagree -------------------------
    rows = measure_cache[corpus]["gpt2"]
    p("\n### Why they disagree: the denominators are not language-neutral")
    p("")
    p("| lang | words/sentence | graphemes/sentence | bytes/sentence | "
      "graphemes/word | bytes/grapheme |")
    p("|---|---|---|---|---|---|")
    for lang in T.LANGS:
        u = rows[lang]["units"]; n = rows[lang]["n"]
        p(f"| {lang} | {u['word']/n:.2f} | {u['grapheme']/n:.1f} | {u['byte']/n:.1f} | "
          f"{u['grapheme']/u['word']:.2f} | {u['byte']/u['grapheme']:.2f} |")
    p("")
    ew = rows["eng"]["units"]["word"]
    worst = min(T.LANGS[1:], key=lambda l: rows[l]["units"]["word"])
    p(f"The same 1012 meanings are packed into {ew} English words but only "
      f"{rows[worst]['units']['word']} {worst} words "
      f"({rows[worst]['units']['word']/ew:.2f}x). A 'word' is not a fixed amount "
      f"of content, so 'tokens per word' silently divides by a different thing "
      f"in every row.")
    return


def main():
    global measure_cache
    ap = argparse.ArgumentParser()
    ap.add_argument("--corpus", default="all", choices=["all", "flores", "in22"])
    ap.add_argument("--tokenizer", default=None)
    a = ap.parse_args()

    corpora = ["flores", "in22"] if a.corpus == "all" else [a.corpus]
    if a.tokenizer:
        for k in list(T.TOKENIZERS):
            if k != a.tokenizer:
                del T.TOKENIZERS[k]

    measure_cache = {c: {t: measure(c, t) for t in T.TOKENIZERS} for c in corpora}

    out = ["# A3 -- corrected cross-language tokenizer comparison",
           "", "Generated by `analyze.py`. Micro-averaged (sum tokens / sum units).",
           "`cost vs eng` = total tokens for the whole corpus divided by total",
           "tokens for the *same sentences* in English -- i.e. the only column",
           "that holds content constant.", ""]
    for c in corpora:
        emit(c, out)

    os.makedirs(RES, exist_ok=True)
    with open(os.path.join(RES, "a3_analysis.md"), "w") as f:
        f.write("\n".join(out) + "\n")

    with open(os.path.join(RES, "a3_analysis.csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["corpus", "tokenizer", "lang", "n_sentences", "tokens"]
                   + [f"tok_per_{u}" for u in UNITS] + ["cost_vs_eng"])
        for c in corpora:
            for t in T.TOKENIZERS:
                rr = measure_cache[c][t]
                for lang in T.LANGS:
                    r = rr[lang]
                    w.writerow([c, t, lang, r["n"], r["tokens"]]
                               + [f"{r['rates'][u]:.6f}" for u in UNITS]
                               + [f"{r['tokens']/rr['eng']['tokens']:.4f}"])
    print(f"\nwrote {RES}/a3_analysis.md and a3_analysis.csv")


measure_cache = {}
if __name__ == "__main__":
    main()
